from __future__ import annotations
import numpy as np
import pandas as pd
from .sofiev_tuner import SofievTuner

def export_fortran_lut(tuner: SofievTuner, filename: str = "sofiev_smart_lut.txt"):
    """
    Generates a 2D Lookup Table (FRP vs Wind) for Fortran usage.
    Assumes mean H_abl and N_ft for the static table.

    Parameters
    ----------
    tuner : SofievTuner
        An instance of the SofievTuner class.
    filename : str, optional
        The name of the output file, by default "sofiev_smart_lut.txt".
    """
    print(f"\n--- Exporting Fortran LUT to {filename} ---")

    # LUT Axes
    frp_axis = np.linspace(50, 5000, 50)
    wind_axis = np.linspace(0, 25, 25)

    # Background Mean Conditions (Static assumptions for 2D LUT)
    # In a fully dynamic system, you might pass these into the RF at runtime in Python
    mean_habl = 1500.0
    mean_nft = 0.012

    with open(filename, 'w') as f:
        f.write("! Smart Sofiev Tuning Table (Generated by ML)\n")
        f.write(f"! Axis 1: FRP (MW) [{len(frp_axis)} bins]\n")
        f.write(f"! Axis 2: Wind (m/s) [{len(wind_axis)} bins]\n")
        f.write("! Columns: FRP  WIND  BETA\n")

        for frp in frp_axis:
            for w in wind_axis:
                # Construct Input Vector
                # Note: We need to project this synthetic point into PCA space
                # to get PC1/PC2.
                raw_vec = np.array([[np.log10(frp), mean_habl, mean_nft, w]])
                scaled_vec = tuner.scaler.transform(raw_vec)
                pca_vec = tuner.pca.transform(scaled_vec)

                input_df = pd.DataFrame([{
                    'log_frp': np.log10(frp),
                    'wind_speed': w,
                    'h_abl': mean_habl,
                    'n_ft': mean_nft,
                    'PC1': pca_vec[0,0],
                    'PC2': pca_vec[0,1]
                }])

                pred_beta = tuner.rf_model.predict(input_df)[0]
                f.write(f"{frp:.1f}  {w:.1f}  {pred_beta:.4f}\n")

    print("   Export Complete.")
